### ISSUE TITLE
A problem with `example/resnet20.py`.

### ISSUE THREAD

**Issue by ninfueng** [PannenetsF/TQT#1]
Hello,
I think there is a problem with `example/resnet20.py`. I tried to run this example and I got an error as below:

```
Traceback (most recent call last):
  File "/home/ninnart/github/TQT/example/resnet20.py", line 126, in <module>
    net = resnet20()
  File "/home/ninnart/github/TQT/example/resnet20.py", line 122, in resnet20
    return ResNet(BasicBlock, [3, 3, 3], **kwargs)
  File "/home/ninnart/github/TQT/example/resnet20.py", line 71, in __init__
    self.layer1 = self._make_layer(block, 16, layers[0])
  File "/home/ninnart/github/TQT/example/resnet20.py", line 95, in _make_layer
    block(inplanes=self.inplanes,
  File "/home/ninnart/github/TQT/example/resnet20.py", line 27, in __init__
    self.conv1 = conv3x3(inplanes, planes, stride=stride)
  File "/home/ninnart/github/TQT/example/resnet20.py", line 13, in conv3x3
    return adder2d(in_planes,
TypeError: __init__() got an unexpected keyword argument 'bias'
```

From the constructor in `Adder2D`  in `tqt.function`, there does not contain `bias` input. However, there is a `bias` argument as below:

https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/example/resnet20.py#L18

Maybe this causes the problem?

**Comment by PannenetsF** [comment]
Thanks for your feedback! For convenience, we add 'bias' attribution to the 'Adder2d' operator as it is in 'Conv2d'.&nbsp; But the bias in a add function is not essential. I will check this issue, thx! :)



---Original---
From: "Ninnart ***@***.***&gt;
Date: Mon, Oct 4, 2021 13:15 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [PannenetsF/TQT] A problem with `example/resnet20.py`. (#1)




 
Hello,
 I think there is a problem with example/resnet20.py. I tried to run this example and I got an error as below:
 Traceback (most recent call last):   File "/home/ninnart/github/TQT/example/resnet20.py", line 126, in <module&gt;     net = resnet20()   File "/home/ninnart/github/TQT/example/resnet20.py", line 122, in resnet20     return ResNet(BasicBlock, [3, 3, 3], **kwargs)   File "/home/ninnart/github/TQT/example/resnet20.py", line 71, in __init__     self.layer1 = self._make_layer(block, 16, layers[0])   File "/home/ninnart/github/TQT/example/resnet20.py", line 95, in _make_layer     block(inplanes=self.inplanes,   File "/home/ninnart/github/TQT/example/resnet20.py", line 27, in __init__     self.conv1 = conv3x3(inplanes, planes, stride=stride)   File "/home/ninnart/github/TQT/example/resnet20.py", line 13, in conv3x3     return adder2d(in_planes, TypeError: __init__() got an unexpected keyword argument 'bias'  
From the constructor in Adder2D  in tqt.function, there does not contain bias input. However, there is a bias argument as below:
 
https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/example/resnet20.py#L18
 
Maybe this causes the problem?

**Comment by PannenetsF** [comment]
Well, I find the bias argument a way to be compatible with the original resnet(Conv2d version). So I decide to keep it and raise error as bias is not None.

**Comment by PannenetsF** [comment]
It has been fixed now.
