### ISSUE TITLE
Type problems in `tqt/function/number.py`

### ISSUE THREAD

**Issue by ninfueng** [PannenetsF/TQT#2]
Hello,

I tried to use a script `QuantizationPool/examples/tqt/resnet20/qunat_tqt.py` from your other repository, `QuantizationPool`, that also utilizes this `TQT` repository. Unfortunately, I got errors as below:

```
Traceback (most recent call last):                                                                                    
  File "quant_tqt.py", line 198, in <module>                                                                          
    train(net, loss_function, optimizer, train_loader, i)                                                             
  File "quant_tqt.py", line 135, in train                                                                             
    loss.backward()                                                                                                   
  File "/home/ninnart/.conda/envs/torch/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward      
    torch.autograd.backward(self, gradient, retain_graph, create_graph)                                               
  File "/home/ninnart/.conda/envs/torch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag                                                                 
  File "/home/ninnart/.conda/envs/torch/lib/python3.6/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)                                                                    
  File "/home/ninnart/github/TQT/tqt/function/number.py", line 99, in backward                                   
    grad_s = (rounded - x_div_s) * cmp0 + n * cmp1 + p * cmp2                                                         
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Bool         
```

There are type errors from mismatch operations between `float` and `bool.` I was able to detect them in the following lines of code in `tqt/function/number.py`.

https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/tqt/function/number.py#L58-L60

and
https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/tqt/function/number.py#L89-L91

In general, these lines of code produce `tensor`s with `dtype bool`. I was able to fix these errors by converting them to `float` as shown below:

```python
cmp0 = ((n <= rounded) & (rounded <= p)).to(torch.float32)
cmp1 = (rounded < n).to(torch.float32)
cmp2 = (rounded > p).to(torch.float32)
```

**Comment by PannenetsF** [comment]
I guess it is a version compatibility issue, and the quant-dequant functions have been test under my own conda environment.&nbsp;
I will finish my vacation in a week, and response of version/environment will arrive then.
Thx! :)



---Original---
From: "Ninnart ***@***.***&gt;
Date: Mon, Oct 4, 2021 15:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [PannenetsF/TQT] Type problems in `tqt/function/number.py` (#2)




 
Hello,
 
I tried to use a script QuantizationPool/examples/tqt/resnet20/qunat_tqt.py from your other repository, QuantizationPool, that also utilizes this TQT repository. Unfortunately, I got errors as below:
 Traceback (most recent call last):                                                                                       File "quant_tqt.py", line 198, in <module&gt;                                                                               train(net, loss_function, optimizer, train_loader, i)                                                                File "quant_tqt.py", line 135, in train                                                                                  loss.backward()                                                                                                      File "/home/ninnart/.conda/envs/torch/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward           torch.autograd.backward(self, gradient, retain_graph, create_graph)                                                  File "/home/ninnart/.conda/envs/torch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward     allow_unreachable=True)  # allow_unreachable flag                                                                    File "/home/ninnart/.conda/envs/torch/lib/python3.6/site-packages/torch/autograd/function.py", line 77, in apply     return self._forward_cls.backward(self, *args)                                                                       File "/home/ninnart/github/TQT/tqt/function/number.py", line 99, in backward                                        grad_s = (rounded - x_div_s) * cmp0 + n * cmp1 + p * cmp2                                                          RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Bool           
There are type errors from mismatch operations between float and bool. I was able to detect them in the following lines of code in tqt/function/number.py.
 
https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/tqt/function/number.py#L58-L60
 
and
 https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/tqt/function/number.py#L89-L91
 
In general, these lines of code produce tensors with dtype bool. I was able to fix these errors by converting them to float as shown below:
 cmp0 = ((n <= rounded) &amp; (rounded <= p)).to(torch.float32) cmp1 = (rounded < n).to(torch.float32) cmp2 = (rounded &gt; p).to(torch.float32)

**Comment by ninfueng** [comment]
I think so. Just to note, I used `torch=1.2.0` and `ppc64le`.

**Comment by PannenetsF** [comment]
I have just checked the torch version **1.7.1** of our **x86_64** servers. Torch after 1.6.x should work with this repo. By the way, the nondifferentiable operations like floor, round have built-in backward functions in torch now. So some of the quant functions could be removed.

**Comment by ninfueng** [comment]
That is interesting. I think you can include a `torch` version requirement into your `README.md` or maybe use an if-cause statement with the `torch` version and support both new and old versions.

**Comment by PannenetsF** [comment]
Yes, I am working on this.
